healthcare:
  target: dev
  outputs:
    dev:
      type: trino
      method: jwt
      host: "{{ env_var('TRINO_HOST', 'trino.upcloud.playground.dataminded.cloud') }}"
      port: 443
      http_scheme: https
      database: iceberg
      schema: demo
      threads: 1
      user: "374073189749817803" #Admin user
      jwt_token: "{{ env_var('TRINO_JWT_TOKEN') }}"
